export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_CONNECT = 'USER_CONNECT';
export const SET_USER_NOTIFICATIONS = 'SET_USER_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const USER_DISCONNECT = 'USER_DISCONNECT';
